-- MySQL Script generated by MySQL Workbench
-- Wed May 23 20:44:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema heroku_373b41bf2fad8f1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_373b41bf2fad8f1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_373b41bf2fad8f1` DEFAULT CHARACTER SET utf8 ;
USE `heroku_373b41bf2fad8f1` ;

-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`usuario` (
  `idUsuario` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `nComercio` VARCHAR(60) NULL,
  `email` VARCHAR(30) NOT NULL,
  `tipoUsuario` SMALLINT NOT NULL DEFAULT 0,
  `fechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `nUsuario_UNIQUE` (`email` ASC),
  UNIQUE INDEX `nComercio_UNIQUE` (`nComercio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`telefono` (
  `idUsuario` VARCHAR(30) NOT NULL,
  `nTelefono` VARCHAR(13) NOT NULL,
  `estado` SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUsuario`, `nTelefono`),
  UNIQUE INDEX `nTelefono_UNIQUE` (`nTelefono` ASC),
  CONSTRAINT `FK_idUsuario_telefono`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `heroku_373b41bf2fad8f1`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`provincia` (
  `idProvincia` SMALLINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`canton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`canton` (
  `idCanton` SMALLINT NOT NULL AUTO_INCREMENT,
  `idProvincia` SMALLINT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCanton`),
  INDEX `FK_idProvincia_idx` (`idProvincia` ASC),
  CONSTRAINT `FK_idProvincia_canton`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `heroku_373b41bf2fad8f1`.`provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`distrito` (
  `idDistrito` SMALLINT NOT NULL AUTO_INCREMENT,
  `idCanton` SMALLINT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idDistrito`),
  INDEX `FK_idCanton_idx` (`idCanton` ASC),
  CONSTRAINT `FK_idCanton_distrito`
    FOREIGN KEY (`idCanton`)
    REFERENCES `heroku_373b41bf2fad8f1`.`canton` (`idCanton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`direccion` (
  `idDireccion` SMALLINT NOT NULL AUTO_INCREMENT,
  `idUsuario` VARCHAR(30) NOT NULL,
  `idDistrito` SMALLINT NOT NULL,
  `dExacta` VARCHAR(150) NOT NULL,
  `estado` SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idDireccion`),
  INDEX `FK_idUsuario_idx` (`idUsuario` ASC),
  INDEX `FK_idDistrito_idx` (`idDistrito` ASC),
  CONSTRAINT `FK_idUsuario_direccion`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `heroku_373b41bf2fad8f1`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idDistrito_direccion`
    FOREIGN KEY (`idDistrito`)
    REFERENCES `heroku_373b41bf2fad8f1`.`distrito` (`idDistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`compra` (
  `idCompra` SMALLINT NOT NULL AUTO_INCREMENT,
  `idComprador` VARCHAR(30) NOT NULL,
  `idDireccion` SMALLINT NOT NULL,
  `fechaHora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tipoEntrega` SMALLINT NOT NULL,
  `guia` VARCHAR(15) NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `FK_idComprador_idx` (`idComprador` ASC),
  INDEX `FK_idDireccion_idx` (`idDireccion` ASC),
  CONSTRAINT `FK_idComprador_compra`
    FOREIGN KEY (`idComprador`)
    REFERENCES `heroku_373b41bf2fad8f1`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idDireccion_compra`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `heroku_373b41bf2fad8f1`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`categoria` (
  `idCategoria` SMALLINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `estado` SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`producto` (
  `idProducto` SMALLINT NOT NULL AUTO_INCREMENT,
  `idVendedor` VARCHAR(30) NOT NULL,
  `idCategoria` SMALLINT NOT NULL,
  `marca` VARCHAR(60) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `precio` INT NOT NULL,
  `existencia` INT NOT NULL,
  `duracionEnvio` VARCHAR(12) NOT NULL DEFAULT '6-12 Horas',
  `tarifaEnvio` INT NOT NULL DEFAULT 0,
  `imagen` VARCHAR(300) NOT NULL,
  `fechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idProducto`),
  INDEX `Fk_idVendedor_idx` (`idVendedor` ASC),
  INDEX `FK_idCategoria_idx` (`idCategoria` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  CONSTRAINT `Fk_idVendedor_producto`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `heroku_373b41bf2fad8f1`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idCategoria_producto`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `heroku_373b41bf2fad8f1`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`solicitud` (
  `idSolicitud` SMALLINT NOT NULL AUTO_INCREMENT,
  `idVendedor` VARCHAR(30) NOT NULL,
  `tipoSolicitud` SMALLINT NOT NULL DEFAULT 0,
  `descripcion` VARCHAR(150) NOT NULL,
  `estado` SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idSolicitud`),
  INDEX `FK_idVendedor_idx` (`idVendedor` ASC),
  CONSTRAINT `FK_idVendedor_solicitud`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `heroku_373b41bf2fad8f1`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`compra_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`compra_producto` (
  `idCompra` SMALLINT NOT NULL,
  `idProducto` SMALLINT NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idCompra`, `idProducto`),
  INDEX `idProducto_compraProducto_idx` (`idProducto` ASC),
  CONSTRAINT `idProducto_compraProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `heroku_373b41bf2fad8f1`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompra_compraProducto`
    FOREIGN KEY (`idCompra`)
    REFERENCES `heroku_373b41bf2fad8f1`.`compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`carrito` (
  `idCarrito` SMALLINT NOT NULL AUTO_INCREMENT,
  `idUsuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCarrito`),
  INDEX `idUsuario_carrito_idx` (`idUsuario` ASC),
  CONSTRAINT `idUsuario_carrito`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `heroku_373b41bf2fad8f1`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`tarjeta` (
  `idTarjeta` SMALLINT NOT NULL AUTO_INCREMENT,
  `idUsuario` VARCHAR(30) NOT NULL,
  `nTarjeta` INT NOT NULL,
  `fExpiracion` CHAR(5) NOT NULL,
  `estado` SMALLINT NOT NULL,
  PRIMARY KEY (`idTarjeta`, `idUsuario`),
  UNIQUE INDEX `nTarjeta_UNIQUE` (`nTarjeta` ASC),
  INDEX `idUsuario_tarjetas_idx` (`idUsuario` ASC),
  CONSTRAINT `idUsuario_tarjetas`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `heroku_373b41bf2fad8f1`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_373b41bf2fad8f1`.`carrito_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_373b41bf2fad8f1`.`carrito_producto` (
  `idCarrito` SMALLINT NOT NULL,
  `idProducto` SMALLINT NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idCarrito`, `idProducto`),
  INDEX `fk_prodcto_cp_idx` (`idProducto` ASC),
  CONSTRAINT `fk_carrito_cp`
    FOREIGN KEY (`idCarrito`)
    REFERENCES `heroku_373b41bf2fad8f1`.`carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prodcto_cp`
    FOREIGN KEY (`idProducto`)
    REFERENCES `heroku_373b41bf2fad8f1`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
